### ISSUE TITLE
What am I missing? Flow Control Tests

### ISSUE THREAD

**Issue by lilyxling** [learn-co-curriculum/skills-based-javascript-intro-to-flow-control#40]
Hi! I'm having trouble passing the lab for Flow Control. Here is the code below for the first two:

function basicTeenager(age){
  if basicTeenager (age => 13 &&  age <=19) {
return "You are a teenager!"
}

function teenager(age){
  if teenager(age => 13 && age <= 19)}
  return "You are a teenager!" {
  else if {
  return "You are not a teenager"
}

I am getting a "ReferenceError: basicTeenager is not defined                                              
      at Context.it (test/flow-control-test.js:26:14)   "

Please help!

**Comment by indigoes** [comment]
I'm having the same issue - did you ever find a resolution?

**Comment by DejanPapez** [comment]
Yes me too. What's the problem?

**Comment by DejanPapez** [comment]
Proposal: 1) use >= instead of =>; 2) add semicolon.

**Comment by indigoes** [comment]
that did not work - still have the same context.it error

![image](https://cloud.githubusercontent.com/assets/25351222/23222645/94a6f560-f8f6-11e6-8679-9ea99461e08d.png)

function basicTeenager(age) {
  if (age >= 13 && age <= 19) {
      return 'You are a teenager!'}
}

function teenager(age) {
  if (age <= 13 && age <= 19) {
    return "You are a teenager!"}
    else {
    return "You are not a teenager"}
}

function ageChecker(age) {
  if (age >= 13 && age <= 19) {
    return "You are a teenager!"}
  else if (age <= 12) {
    return "You are a kid" }
  else (age >= 20) {
    return "You are a grownup"}
}

function ternaryTeenager(age) {
  if (age >= 13 && age <= 19) {
    return "You are a teenager"
  }
  return "You are not a teenager"
  }


function switchAge(age) {
switch(age) {
  case (age >= 13 && age <= 19):
  return ("You are a teenager");
  break;
  default:
  return ('You have an age')
  break;
}
}

**Comment by karnikad** [comment]
I am getting the same issue. Any solution?

**Comment by BigBankElit3** [comment]
same issue here.

**Comment by vcorvington** [comment]
See below for solution to JavaScript Flow Control lesson:


function basicTeenager(age) {
if (age >= 13 && age <= 19) {
  return "You are a teenager!";
}
}


function teenager(age) {
  if (age >= 13 && age <= 19) {
    return "You are a teenager!";
  } else {return "You are not a teenager";}
}

function ageChecker(age) {
  if (age >= 13 && age <= 19) {
    return "You are a teenager!";
  } else if (age <= 12) {
    return "You are a kid";
  } else {return "You are a grownup";}
  }

function ternaryTeenager(age) {
  if (age >= 13 && age <= 19) {
    return "You are a teenager";
  } else {return "You are not a teenager";}
}


function switchAge(age) {
switch(age) {
  case 13:
  return "You are a teenager"

  case 14:
  return "You are a teenager"

  case 15:
  return "You are a teenager"

  case 16:
  return "You are a teenager"

  case 17:
  return "You are a teenager"

  case 18:
  return "You are a teenager"

  case 19:
  return "You are a teenager"
  default:
  return "You have an age"
}
}

**Comment by mdo5004** [comment]
Same issue

**Comment by JessRudder** [comment]
Hi @lilyxling @indigoes @karnikad @BigBankElit3 @mdo5004 

The error that you're seeing is usually one of two things:

1) The function has not been defined.  Sometimes this could be a typo in the function name `basicTenager` vs `basicTeenager`.  Make sure to double check that the function definition is there and that it is named exactly the same as what the test is calling for.

2) There is a syntax error that is preventing the JavaScript compiler from reading the function (which means that function is not defined later when the code tries to call it).  In one set of the code provided above, using `=>` instead of `>=` is incorrect syntax and would cause this issue. 

Try copying and pasting your code into the JavaScript console in Chrome to see if it shows any syntax errors.

**Comment by mdo5004** [comment]
My issue was having a single syntax issue, which I discovered by pasting my script into repl.it. A syntax error made my entire code fail to compile, so none of my functions were defined.

**Comment by jaywood128** [comment]
Can anyone help me understand what is wrong? I am failing all of the 11 tests. I used repl.it as recommended, and the issue came up on line 12. I formatted each one the same way, but it's saying unmatched {.  


function basicTeenager(age) {
  if (age >= 13 && age <= 19) {
    return "You are a teenager!";
}
}
function teenager(age) {
  if (age>=13 && age <= 19){
  return "You are a teenager!";
}  else {return "You are not a teenager";}
}

function ageChecker(age) {
  if (age>=13 && age <= 19){
  return "You are a teenager!";
} else if (age <= 12){
  return "You are a kid";
} else {return "You are a grownup";
}

function ternaryTeenager(age) {
  if (age >= 13 && age <= 19){
    return "You are a teenager";
  } else {return "You are not a teenager";}

}

function switchAge(age) {
  switch(age){
    case 13:
    return "You are a teenager";

case 14:
return "You are a teenager";

case 15:
return "You are a teenager";

case 16:
return "You are a teenager";

case 17:
return "You are a teenager";

case 18:
return "You are a teenager";

case 19:
return "You are a teenager";

default:
return "You have an age";
}
}

**Comment by mdo5004** [comment]
else {return "You are a grownup";

Should be

else {return "You are a grownup";}

**Comment by jaywood128** [comment]
Thank you mdo5004!! I was able to pass the lab.

**Comment by mashuka** [comment]
im having issues with the last function. i have passed the previous ones but whenever i try to copy any of the above solutions it says  7 passing 4 failing (meaning the previous 4 fails this time )

**Comment by Ncaponi** [comment]
i am struggling with great difficulty passing this Lab, can anyone please help!
